NumPy Advanced

This notebook covers reorganising arrays, random numbers & basic simulations 

In [2]:
import numpy as np

### Reorganising arrays

In [5]:
b = np.array([[1,11,111,1111],[2,22,222,2222]])
b

array([[   1,   11,  111, 1111],
       [   2,   22,  222, 2222]])

In [9]:
# Reshape
a = b.reshape(4,2)
a

array([[   1,   11],
       [ 111, 1111],
       [   2,   22],
       [ 222, 2222]])

In [19]:
# Vertical stacking
v1 = np.full((2,3), 5)
v2 = np.full((2,3), 10)
np.vstack([v1,v2,v1])

array([[ 5,  5,  5],
       [ 5,  5,  5],
       [10, 10, 10],
       [10, 10, 10],
       [ 5,  5,  5],
       [ 5,  5,  5]])

In [20]:
# Horizontal stacking
np.hstack([v1,v2])

array([[ 5,  5,  5, 10, 10, 10],
       [ 5,  5,  5, 10, 10, 10]])

### Random Numbers

In [22]:
#default_rng()
rng = np.random.default_rng()
rng

Generator(PCG64) at 0x1F4A8FAA180

In [27]:
rng.random()

0.9300363804820454

In [33]:
print(rng.integers(1, 10))

9


In [41]:
print(rng.uniform(1, 10, size = (3,2)))

[[6.55074556 7.08921599]
 [7.65653997 2.34045991]
 [7.34734241 2.77631733]]


Seed

In [46]:
rng1 = np.random.default_rng(seed=100)
rng1.random()

0.8349816305020089

In [47]:
rng2 = np.random.default_rng(seed=100)
rng2.random()

0.8349816305020089

In [49]:
rng = np.random.default_rng()
rng.integers(3)

np.int64(2)

In [84]:
rng = np.random.default_rng()
for i in range(10):
    random_int = rng.integers(3)
    print(random_int)

1
2
2
2
0
2
1
2
2
1


In [88]:
for count in range(5):
    random_int1 = rng.integers(low=10, high=20, endpoint=True)
    print(random_int1)

19
20
18
15
18


In [93]:
#Random arrays
rng.random(size=(2,3))

array([[0.17384468, 0.76009182, 0.99000186],
       [0.08142637, 0.9189274 , 0.08863953]])

In [96]:
rng.uniform(size=(2, 3), low=-20, high=-19.9999)

array([[-19.99999279, -19.99997949, -19.99997989],
       [-19.99992588, -19.99992363, -19.99995096]])

In [100]:
#Randomizing Existing NumPy Arrays
a = np.array([1,2,3,4,5,6,7,8,9,10])
rng.choice(a, size = (2,2), replace = True)

array([[5, 3],
       [2, 2]])

In [107]:
b = np.array([[1, 2, 3, "a" ], [4, 5, 6, "b"], [7, 8, 9, "c"], [10, 11, 12, "d"]])
b #all elements will be converted to string.

array([['1', '2', '3', 'a'],
       ['4', '5', '6', 'b'],
       ['7', '8', '9', 'c'],
       ['10', '11', '12', 'd']], dtype='<U21')

In [108]:
rng.choice(b, size=2)

array([['1', '2', '3', 'a'],
       ['1', '2', '3', 'a']], dtype='<U21')

In [111]:
rng.choice(b, size=2, replace = False)

array([['7', '8', '9', 'c'],
       ['4', '5', '6', 'b']], dtype='<U21')

In [117]:
rng.choice(b, size=2, replace = False, axis = 1)

array([['1', '2'],
       ['4', '5'],
       ['7', '8'],
       ['10', '11']], dtype='<U21')

In [150]:
#shuffle parameter
g = (["a","b","c","d","e"])
rng.shuffle(g)
print(g)

['a', 'c', 'b', 'd', 'e']


### Basic Simulations

In [182]:
#Large no. of trials give accurate results
coin_flips = np.random.randint(0, 2, size=10000)
a = coin_flips.mean()
print(a)
coin_flips1 = np.random.randint(0, 2, size=100)
b = coin_flips1.mean()
print(b)

0.4993
0.57


In [190]:
#Normal distribution
np.random.normal(loc=0, scale=1, size=10000)
#These random no. follow bell-shaped curve

array([-3.28892190e-01, -2.13064655e-03,  9.57541998e-01, ...,
       -1.08990384e+00,  2.54214019e+00,  1.14511901e+00], shape=(10000,))

In [192]:
#Poisson distribution
np.random.poisson(lam=4, size=10000)
#The random no. so formed represent how many times an event occured ina fixed interval of time

array([4, 3, 3, ..., 4, 3, 3], shape=(10000,), dtype=int32)

In [205]:
#Simulation of pi
##first we simulate n random points
n = 100000
x = np.random.random(n)
y = np.random.random(n)

##then we count points inside quarter circle
inside = (x**2 + y**2) <= 1
pi_estimate = 4 * np.sum(inside) / n
pi_estimate

np.float64(3.1416)