Load in NumPy

In [2]:
import numpy as np

### Basics

In [11]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[7.9,8.1,5.5],[5,5,5.55]])
print(b)

[[7.9  8.1  5.5 ]
 [5.   5.   5.55]]


To get Dimensions

In [7]:
b.ndim

2

To get Shape

In [8]:
a.shape

(3,)

In [9]:
#Get Type
b.dtype

dtype('float64')

To get Size

In [10]:
a.itemsize

8

In [12]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [13]:
a.itemsize

2

In [15]:
a = np.array([1,2,3], dtype='int32')
print(a)
a.itemsize

[1 2 3]


4

To get total size

In [19]:
a.size*a.itemsize
a.nbytes

12

### Accessing / Slicing / Changing specific rows, columns

In [21]:
a = np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(a)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


To get a specific element

In [33]:
a[0, 2]

np.int64(6)

In [30]:
#Specific column
a[0:,2]

array([6, 5])

In [31]:
#Specific row
a[1,:]

array([1, 3, 5, 7, 9])

In [35]:
#[start:stop:step]
a[1,0:5:2]

array([1, 5, 9])

In [3]:
b =np.array([[[2, 4],[6, 8]],[[1, 3],[5, 7]]])
print(b)

[[[2 4]
  [6 8]]

 [[1 3]
  [5 7]]]


In [39]:
#To get 8
b[0,1,1]

np.int64(8)

Replace

In [9]:
b[1,0,:] = [11,33]

In [10]:
b

array([[[ 2,  4],
        [ 6,  8]],

       [[11, 33],
        [ 5,  7]]])

### Initializing Different Arrays

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.full((3,6), 55.5)

array([[55.5, 55.5, 55.5, 55.5, 55.5, 55.5],
       [55.5, 55.5, 55.5, 55.5, 55.5, 55.5],
       [55.5, 55.5, 55.5, 55.5, 55.5, 55.5]])

In [14]:
np.random.rand(4,5)

array([[0.23236538, 0.76977998, 0.78985069, 0.52485103, 0.04089373],
       [0.87149937, 0.5141953 , 0.79457226, 0.64404806, 0.77860766],
       [0.86954753, 0.40094766, 0.47406165, 0.03137941, 0.32423322],
       [0.18004896, 0.40766092, 0.97121211, 0.35491283, 0.06527077]])

In [15]:
np.random.randint(5, size=(2,2))

array([[4, 4],
       [1, 0]], dtype=int32)

The identity matrix

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Repating an array

In [18]:
ar1 = np.array([[5, 50, 500]])
rep1 = np.repeat(ar1, 4, axis=0)
print(rep1)

[[  5  50 500]
 [  5  50 500]
 [  5  50 500]
 [  5  50 500]]


In [24]:
ar1 = np.array([[[[5, 50, 500]]]])
rep1 = np.repeat(ar1, 4, axis=0)
print(rep1)

[[[[  5  50 500]]]


 [[[  5  50 500]]]


 [[[  5  50 500]]]


 [[[  5  50 500]]]]


### copy()

In [26]:
a = np.array([1,3,5])
b = a
b

array([1, 3, 5])

In [27]:
b[2]=21
b

array([ 1,  3, 21])

In [28]:
a

array([ 1,  3, 21])

In [30]:
a = np.array([1,3,5])
b = a.copy()
b[2]=21
b

array([ 1,  3, 21])

In [31]:
a

array([1, 3, 5])

### Vector Operations

In [38]:
y = np.array([1, 21, 96, 559])
y

array([  1,  21,  96, 559])

In [39]:
y += 20
y

array([ 21,  41, 116, 579])

In [40]:
y / 7

array([ 3.        ,  5.85714286, 16.57142857, 82.71428571])

In [41]:
x = ([9, 9, 34, 21])
y + x

array([ 30,  50, 150, 600])

In [42]:
np.sin(x)

array([0.41211849, 0.41211849, 0.52908269, 0.83665564])

### Statistics 

In [43]:
s = np.array([[1,2,12],[3,4,34]])
s

array([[ 1,  2, 12],
       [ 3,  4, 34]])

In [44]:
np.min(s)

np.int64(1)

In [45]:
np.max(s)

np.int64(34)

In [49]:
np.max(s, axis=1)

array([12, 34])

In [50]:
np.sum(s)

np.int64(56)

In [53]:
np.sum(s, axis = 0)

array([ 4,  6, 46])

In [54]:
np.mean(s)

np.float64(9.333333333333334)

In [56]:
np.var(s)

np.float64(134.55555555555554)

In [57]:
np.std(s)

np.float64(11.599808427536876)